from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

from code_atlas.writers.context import RepoContext

_TEMPLATE_DIR = Path(__file__).parent / "templates"
_env = Environment(
    loader=FileSystemLoader(_TEMPLATE_DIR),
    autoescape=select_autoescape(enabled_extensions=()),
    trim_blocks=True,
    lstrip_blocks=True,
)

_CLAUDE_APPEND = "\n<!-- Generated by code-atlas. Re-run `code-atlas index` to refresh. -->\n"


def render(ctx: RepoContext, *, claude_specific: bool = False) -> str:
    body = _env.get_template("base.md.j2").render(ctx=ctx)
    return body + _CLAUDE_APPEND if claude_specific else body


def write(ctx: RepoContext, repo_root: Path) -> Path:
    path = repo_root / "CLAUDE.md"
    path.write_text(render(ctx, claude_specific=True))
    return path
